In [2]:
import pandas as pd
import os

In [3]:
train_dir = "E:\master\\final_project\data\my_data\start_here\\fold_5\\train\\data.csv"
test_dir = "E:\master\\final_project\data\my_data\start_here\\fold_5\\test\\data.csv"
train_df = pd.read_csv(train_dir)
test_df = pd.read_csv(test_dir)

In [4]:
train_df.describe()

            target
count  1731.000000
mean      0.683420
std       0.465276
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

In [6]:
test_df.describe()

           target
count  434.000000
mean     0.684332
std      0.465318
min      0.000000
25%      0.000000
50%      1.000000
75%      1.000000
max      1.000000

In [7]:
(1731/(434+1731))*100

79.95381062355659